spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/your_database_name
    username: root
    password: Acube@1729
  jpa:
    hibernate:
      ddl-auto: update  # Automatically create/update database schema
    show-sql: true  # Show SQL statements in the console (optional)
